language: python
python:
- '3.6'
install:
- pip install ansible molecule testinfra apache-libcloud gcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/my-key.json"
  global:
  - secure: Ie8ShkuMxA9f9NNDJJkS0Ttn/Am6Sw7HGWDyL439UdRGIxNjqEfDIF1RuPvucWBQy5TEallGY291DjznAdI+Ka+7TlVnu9E1hxWdqAGwzVxxu2Y38F5Dvf4uW6AKiJDIW4imvSYeUuH5Y2slDJnM359tVaQRY1YfPKqm8/Yx5D3JDaULkjLl8M/xvy2WdK5ZrKEUs7I0QN/Ahii0Arnv9WjPViYIou4iHPkprnOOPr+xtziRco7IqiT5VOJ6lu1gh9+CbHEGrN5TifS5xCyFr9uSxKcoH6PRuhFImqALO7S+gmEmOOgYOLm7wo9u9utHDTVDVYldA4sriWL1M200AqCV5SlGXU8h7cniEHpRe1kn9/NgZMk0yWbyhV2ll0WJHfyevWixMB8MPAJpzL/mMuHwzjFwhrYuY76gANAxiHwZ9A7j8rlquj1spAa9H/Z7SkYzR8I9/dHAV67hetkWyqJqmXUWr47WMAhBeMilkzCFdVlZ+k8UE9msns8Srr2i3FoRP6UEpAiYAiN1RXE7O+vYzm9mW/kbzCUhcq3zFpS/nVarAP8eTE+4eH8NPgSIukJrRptPrzMY7yJQkX7zR5rQzebjBSZ/2NZYNeUKWkf4nzx1TDwsBrKXMWs4zInoo/OISA71FIdgYsvfJfJgcWb4RLLDMo++SyBbfidghKE=
  - secure: qUKXILLSJ6g9e1tLjpDZX7Y1rV5Nw6F6tSa0ZviOT08UDpiAOHVwWtCXVtr/G6LwsD7VaDtNFhQ9x7kDKe83eS19NDT0sJGCpgAMvaInpIaKr5NAMlyQT6555TPtsbIyx1zP5DEXiadyGSO9zz8lXMGHh8W4w/VF5AIvoVPpqJKLVzJJgBA47o+RvsmZXFzXg/aG+pQLVE5sjaCyfbAduZR6fzcOSdCNMryUBKX3vSY6zXq86uMu0WIokjM3cqnYp4+bIdr5fcQCJEfx7mIosyMkOJzUgfzaCXIbqGQFnwSJsLG35VfRuep96EF3bpSu6PiAmhZ14eZAUwMlE+s2Vj8RUt4XzD2wMemE5+wD1XZzZlCibRoIsa77wtM7jcvgKyGeIva+y5B/ygR33mVozvCkU2WPBovV/Fucy9LUjxcZCvWWNP6mS6EkGkdgE4A19aFRsud5AnaAFwrqPFH1/fuDlhEO38wFq/hKXyHPU2fJaR+KtJ4eYGnVukmb3izmuAPpJxQIA58pNT6yY3ficpZJLYpHWD5A0xZMnLFYgDrMUlziIymsska/9XwTXe1CkrdrCJDO2iiZIE6GVNS8NIB1bSrOWTQDqYVcDDGLWK3H2WeppFSlpcenjqpYt1I4BOuC/u5Y8EdqjfyDnt1I8ib7k/4jgOGEmlOZZcOK3yw=
  - secure: o/sCQ56E/6BsNugXlcyJ46Md1WdRkUc/S6X5u1y1o2MfpRl1+paHVD9ehEJxuXQm++uORsL2kXY/I0RmAOSGTuCV8H+x3fJggbxvbcRwa7F43sLH6EQMaUlOBzxBcV3t3Kn8Q0GWKB9yNRtmkmYhFHjdS93UjUX80sg+iEvIMm+EkGHFC661MiicZff/aL86KvEZGLE9agoTCVPWL6XsU1U+BH+WuhQ6XBNTpHZ1BpqTLby92Hl4BfRZl5lKx9GhCiGZujtcSX3GoolHZTYpLt0OV/ODLj0TOXwC34+cSHIOXrDaS0+PkZlV0utsVO+CxFsRG9kg4csUkzGzvjtrT/S40ODgG1+cLpXb7owUkuMKUJpekFQJmISPrrwdPL0eqwQMH35axqBop5uWgfIP3qneM4sL/Za3gxZvjs50ijBnEbWUXSCp2pGrU6vRWcZmTMzWea2aNTL0dPQe6gr1D9ID5eQaXBGxUfvzf8EJHBG01MZ5lYi192qrTh++LPoBpyQU8TLMUE6cW5NkN7SxxFBfhRxDDi+wuysnpG+zUdJR9SbVb5DmEvKQg+4xE9YFrOlAwdqjBpo9TetDLygw1Di653gpgRfp06p35XwlQnabe8zoBfMgeSVN1ilu4hbxbGnxnMNqAxSjadYwJJbpeVuq15x0jgqHaL1XQCKQzRQ=
script:
- cd db
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_f5d22dcaf8cf_key -iv $encrypted_f5d22dcaf8cf_iv
  -in creds.tar.gz.enc -out creds.tar.gz -d
- tar xzvf creds.tar.gz
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    secure: Io6nqIw5SfYMo5Yi5cKigO6JMqLiHY9j/1wlZVv+4asqcaEf7JXP6KX9EKbX+vhbVsX2kpQmChPN1jSOmXa28P0DkfUu0PhBbnW0IpNZLO/OxdBkFZ8i9QUcX9x19tNRhY4qrAwlaYLGdRbnbOFgfgBIPPJsS7MdKoNchcUawvOmHpswAU5p1QJaCNK8eb0TvouZrOC+GU6OTwBenaNp/loyaYYtcQN1LeC+ZxtQAacfWOf3z34okJnoAt7QJCqmX23y2E/Ed+n4HuNJY7k5+y4k1hKL/rbM+5ac8GLskNmMavHbpQHwbRPFNGv22KCLeyR7kyxO6S2g0KMfku0wvrciZccjOwXPFo4X/1KNW+DIwJ7lUvl5oieZWOx4AQF9pHoOjqHs5nKbGTI2DzXQeWnLPZwuS8bf/r9xvY17e1CAY4VSE7FTYjyQyDlMbi1Toglj8iepEbmlb9zJ+Kkm3TLs+xRaSGYDnUs4HKq/sKlkmQnBIW7muZRATBvmwEr+Rpl9jTOLm1Ti8YfBOQBi22LDnUE10ZvYd2ORDRjQ7EqCzjPuNJqjLF1ha1D+q1NpVatc7aWY3zYBF4uzMjOorfOfjTiIilJkayKeTPgSrVxFAE2omu02bk5AbgBg/qlQzwFKAffKMS/YfIWpqm8ZCWRo1Ww8CVTlcpDZA95XI38=
