language: python
python:
- '3.6'
install:
- pip install ansible molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/my-key.json"
  global:
  - secure: Ie8ShkuMxA9f9NNDJJkS0Ttn/Am6Sw7HGWDyL439UdRGIxNjqEfDIF1RuPvucWBQy5TEallGY291DjznAdI+Ka+7TlVnu9E1hxWdqAGwzVxxu2Y38F5Dvf4uW6AKiJDIW4imvSYeUuH5Y2slDJnM359tVaQRY1YfPKqm8/Yx5D3JDaULkjLl8M/xvy2WdK5ZrKEUs7I0QN/Ahii0Arnv9WjPViYIou4iHPkprnOOPr+xtziRco7IqiT5VOJ6lu1gh9+CbHEGrN5TifS5xCyFr9uSxKcoH6PRuhFImqALO7S+gmEmOOgYOLm7wo9u9utHDTVDVYldA4sriWL1M200AqCV5SlGXU8h7cniEHpRe1kn9/NgZMk0yWbyhV2ll0WJHfyevWixMB8MPAJpzL/mMuHwzjFwhrYuY76gANAxiHwZ9A7j8rlquj1spAa9H/Z7SkYzR8I9/dHAV67hetkWyqJqmXUWr47WMAhBeMilkzCFdVlZ+k8UE9msns8Srr2i3FoRP6UEpAiYAiN1RXE7O+vYzm9mW/kbzCUhcq3zFpS/nVarAP8eTE+4eH8NPgSIukJrRptPrzMY7yJQkX7zR5rQzebjBSZ/2NZYNeUKWkf4nzx1TDwsBrKXMWs4zInoo/OISA71FIdgYsvfJfJgcWb4RLLDMo++SyBbfidghKE=
  - secure: qUKXILLSJ6g9e1tLjpDZX7Y1rV5Nw6F6tSa0ZviOT08UDpiAOHVwWtCXVtr/G6LwsD7VaDtNFhQ9x7kDKe83eS19NDT0sJGCpgAMvaInpIaKr5NAMlyQT6555TPtsbIyx1zP5DEXiadyGSO9zz8lXMGHh8W4w/VF5AIvoVPpqJKLVzJJgBA47o+RvsmZXFzXg/aG+pQLVE5sjaCyfbAduZR6fzcOSdCNMryUBKX3vSY6zXq86uMu0WIokjM3cqnYp4+bIdr5fcQCJEfx7mIosyMkOJzUgfzaCXIbqGQFnwSJsLG35VfRuep96EF3bpSu6PiAmhZ14eZAUwMlE+s2Vj8RUt4XzD2wMemE5+wD1XZzZlCibRoIsa77wtM7jcvgKyGeIva+y5B/ygR33mVozvCkU2WPBovV/Fucy9LUjxcZCvWWNP6mS6EkGkdgE4A19aFRsud5AnaAFwrqPFH1/fuDlhEO38wFq/hKXyHPU2fJaR+KtJ4eYGnVukmb3izmuAPpJxQIA58pNT6yY3ficpZJLYpHWD5A0xZMnLFYgDrMUlziIymsska/9XwTXe1CkrdrCJDO2iiZIE6GVNS8NIB1bSrOWTQDqYVcDDGLWK3H2WeppFSlpcenjqpYt1I4BOuC/u5Y8EdqjfyDnt1I8ib7k/4jgOGEmlOZZcOK3yw=
  - secure: o/sCQ56E/6BsNugXlcyJ46Md1WdRkUc/S6X5u1y1o2MfpRl1+paHVD9ehEJxuXQm++uORsL2kXY/I0RmAOSGTuCV8H+x3fJggbxvbcRwa7F43sLH6EQMaUlOBzxBcV3t3Kn8Q0GWKB9yNRtmkmYhFHjdS93UjUX80sg+iEvIMm+EkGHFC661MiicZff/aL86KvEZGLE9agoTCVPWL6XsU1U+BH+WuhQ6XBNTpHZ1BpqTLby92Hl4BfRZl5lKx9GhCiGZujtcSX3GoolHZTYpLt0OV/ODLj0TOXwC34+cSHIOXrDaS0+PkZlV0utsVO+CxFsRG9kg4csUkzGzvjtrT/S40ODgG1+cLpXb7owUkuMKUJpekFQJmISPrrwdPL0eqwQMH35axqBop5uWgfIP3qneM4sL/Za3gxZvjs50ijBnEbWUXSCp2pGrU6vRWcZmTMzWea2aNTL0dPQe6gr1D9ID5eQaXBGxUfvzf8EJHBG01MZ5lYi192qrTh++LPoBpyQU8TLMUE6cW5NkN7SxxFBfhRxDDi+wuysnpG+zUdJR9SbVb5DmEvKQg+4xE9YFrOlAwdqjBpo9TetDLygw1Di653gpgRfp06p35XwlQnabe8zoBfMgeSVN1ilu4hbxbGnxnMNqAxSjadYwJJbpeVuq15x0jgqHaL1XQCKQzRQ=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_f5d22dcaf8cf_key -iv $encrypted_f5d22dcaf8cf_iv -in creds.tar.gz.enc -out creds.tar.gz -d
- tar xzvf creds.tar.gz
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    rooms:
      secure: exe2bjNfeLoFexRHQLKMscZOqfEPA/IucLSKuxxhWVei8yK2B93x9uc9mCG7ryVhVYcPxpc2/t5rYgDKOyXvOiBY3T5IinUuAvkJ/dXIYiizoRkjZ56KCj6xIVAAi+pk1cbHboRi/iBWrruqrHq+1Tyfi5MHLVUTUN4IcB437DRVOXkUVJPRsYE6HeARDueTIa6/JmcEPdmfhob4EbrlXktKe/5xFys+iyym5hIi9xwlsSDeDDFZBiB/3u15tZyPs0semD3wqxOAIUNe8njihQpcxOj8Xon1QDmCC3LaKIDVNfoBO/FGJATNJ7chv6V8eJziJfO/7g0EdNXXkrXHHBD2KBFImPIm8b+KLfux/eQzkj+Uu2a8H+LpX2eWKwBXASkcd1yIhPwucivenaCtEYKwHm+f2dolXHemKZ4+JRPlmLaXUswPm3TVLPo0bYTLDnZqPf1TrVfRZas3ArHkjova/zD5Kxs40qq3BLe7qv06/lq/4ir3UzIw1IOM/Xe4qd7BceHB16+EAEE/IbniEhubUMDoN4Q4SSbIS3QWbUw1IIdtXDgZtqwBZQ1Yf9AUzfQSHn/GcEyju7WUmZgtSkkkXLEpsURuij6tEDGHvdJDMyFWdzcOl9Y95HNwCpgur7cc1zObZ4Puz0lSjpnXdtP5T3GyFHioMqP5BC65q+A=
