language: python
python:
- 3.6
install:
- pip install ansible molecule testinfra apache-libcloud gcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/my-key.json"
  global:
  - secure: ctkw0xNkXB9BD6epuCE2P20eOUODYQ6VDkSyDjdy1iBKsfMEpW43oSpRUnTLL8x0giiCzyp0p8m5D4AqZYqGvKFZ0FJtBDLhmQQdvvNJytBmuW7bStITb6FduAOXwtJE/Of1wdpDbwuxOO/Q5QqHxxnhICz2dSlC9/qABC1h3SNdpVoQS3nUXg1txHrQTffECUZRzCttp6WeQlr0fj/zQB2wQXuC0LJZYKSkHRY0J1P+eD9hhgj/TeUNZFL1rJ/i+lYW/hPxKdnwXOoTwYr/iBIX6mYmfRNUE3d0tyei9h3V7eEQPZ5y48SpfSOucb5bsgWoKeDx8Y1aS58urE/5IwRPUANPYAxO/40oh/RMZ1WJ5l3womY2I8nrBx3a8N4K9FZIzvzJMryg+ixbut3wVWTU1BW45UUiA+ZCn11tMCLF7NY4gq808FkdId94SsCGap1AWhtDKgvwRhBfBi7jgJAzBtr1PWGIel8Mjg/uzO21FuifNp3yHvrotLqoYO5hZzGvavvMUFyrze4DO8/ckkw/ueYkU0LQABE7ylWYQCbOr5PowvX0QyupT2zVqWtkjNiWvFeJTyH0726RlzQT3mIkynhfvP+9SdPrqCVsSKqMWd6dYTnPbNE2DfqWUVQmqIH7la1ThZhhEEOJGrFFtqBstCpbSCewOiujNgTsSV4=
  - secure: fwwaeMcvw+G5Pp06yJj6iZZPa7A1soN+8vvLe8dvjt7atJpj1TrYdxDm8KKM+HrB1Zs73lUFBVRfLlAyvdacHS475s0MsWGqMvlXJzrthIgbM5jgBDAnCvi2VVY6NOnS4X39rlh2Ob/DDcMT4NHy9Ktg2U0LhKjrw5B6zXdFlCiWeQNcq/8a6NULEFKcaUnpvHDsKgJYqQ6L3Ulci2U5V3cge3maYbDa/ABTlnIjUQOw+/YKb1Loz/7Cmo+yK/XzJFkF7kMAH2UvIJkozwLCL86ZSLnJ6x2YLvar6Rf37nEGgGXf/jO6c3Up+/QB7IrxGbIhwjNYQjj2p8bT+12cQSudYefcV4D9+2NRBn5wh1Y1PC64o3bH8K1RIqZkWm1nejjO0c7xUKk7VveSn5+bsCnYhdG/AlmdEcVAIZ5pZxApJjtDadvVBnMVIpuGUnYB++QOQ2bfmdJSZf2qteiP/dDKCjP4d1YRZhpH2nfZI8T1GTB1L1TiZhpnOLhZiYTF9RW5SVXedBbeDiicOLeBsNeJ6vIZcSE1fERpHPh+mj+FjmDbCcMWVG3KNqogauSEXvQ9KFnlu7XKzVFgCVS+b8dd6Eep/wAEkP4cT/TD8NLhhbkvr9rn9M6bvghmhfuVOZjrC8QJfyNxCAPgWOsWuB9/VoWlpusyztOjW8yosJQ=
script:
- molecule --version
- cd db
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_f5d22dcaf8cf_key -iv $encrypted_f5d22dcaf8cf_iv -in creds.tar.gz.enc -out creds.tar.gz -d
- tar xzvf creds.tar.gz
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- cp /home/travis/.ssh/google_compute_engine /home/travis/.ssh/id_rsa
notifications:
  slack:
    secure: Io6nqIw5SfYMo5Yi5cKigO6JMqLiHY9j/1wlZVv+4asqcaEf7JXP6KX9EKbX+vhbVsX2kpQmChPN1jSOmXa28P0DkfUu0PhBbnW0IpNZLO/OxdBkFZ8i9QUcX9x19tNRhY4qrAwlaYLGdRbnbOFgfgBIPPJsS7MdKoNchcUawvOmHpswAU5p1QJaCNK8eb0TvouZrOC+GU6OTwBenaNp/loyaYYtcQN1LeC+ZxtQAacfWOf3z34okJnoAt7QJCqmX23y2E/Ed+n4HuNJY7k5+y4k1hKL/rbM+5ac8GLskNmMavHbpQHwbRPFNGv22KCLeyR7kyxO6S2g0KMfku0wvrciZccjOwXPFo4X/1KNW+DIwJ7lUvl5oieZWOx4AQF9pHoOjqHs5nKbGTI2DzXQeWnLPZwuS8bf/r9xvY17e1CAY4VSE7FTYjyQyDlMbi1Toglj8iepEbmlb9zJ+Kkm3TLs+xRaSGYDnUs4HKq/sKlkmQnBIW7muZRATBvmwEr+Rpl9jTOLm1Ti8YfBOQBi22LDnUE10ZvYd2ORDRjQ7EqCzjPuNJqjLF1ha1D+q1NpVatc7aWY3zYBF4uzMjOorfOfjTiIilJkayKeTPgSrVxFAE2omu02bk5AbgBg/qlQzwFKAffKMS/YfIWpqm8ZCWRo1Ww8CVTlcpDZA95XI38=
